apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          image: gargimadhuawsdocker/gargimadhuawsdocker:latest
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              memory: "2000Mi"
              cpu: "1000m"
